export class Table {
  arrayIndex: string;
  number: string;
  topValue: string;
  leftValue: string;
  bgColor: string;
  isBesetzt: boolean;
  placeholder: boolean;
  department: string;
  border: string;
  width: string;
  height: string;
  borderRadius: string;
  transformValue: string;
  groups: [{
    nameValue: string;
    zimmernummerValue: string;
    anreiseValue: string;
    abreiseValue: string;
    personenAnzahlValue: string;
    notiz1Value: string;
    notiz2Value: string;
    trace: string;
    bemerkungValue: string;
    nationValue: string;
    kategorieValue: string;
    preisTypValue: string;
    reisebueroValue: string;
    spracheValue: string;
    departmentValue: string;
    traceValue: string;
    newTraceText: string;
    newTraceRoomNumber: string;
    newTraceTableNumber: string;
    newTraceEmployee: string;
    newTraceName: string;
    newTraceDate: string;
  }];
}
